### ISSUE TITLE
issue with 2 negative values on p.clipur

### ISSUE THREAD

**Issue by Itaykeidar** [pulp-platform/riscv#104]
We encountered a problem with p.clipur operation. To show this we prepared a simple test program:
 
_start_jmp:
                  li x3, 0xFFFFFFFF
                  li x4, 0xe9e9e9eb
                   p.clipur x2, x3, x4
 write_tohost:
                                nop
 _exit:
                                j write_tohost
 
According to spec:
![Capture](https://user-images.githubusercontent.com/53673889/62420200-06af9d00-b697-11e9-9af5-6fe6d365c97f.PNG)

So I see no restrictions to load negative values to the rs1 or rs2 and moreover there is a check if rs1 is negative or zero. 
In our test we are loading two negatives in the x3 and x4 and using them as rs1 and rs2 of p.clipur operation.
Here are the waves:
![Capture](https://user-images.githubusercontent.com/53673889/62420207-25ae2f00-b697-11e9-8d8c-a8305c7d5dee.PNG)

test flow:
first pulse of ex_reg_we is the li operation which is loading x3 value.
next two pulses are lui and addi operations to load x4 value.
pulse at TimeA point is the actual p.clipur operation execution.
after this at the next cycle we can see p.clipur result at register x2. according to it's value I think that actually was performed rD = rs2. 
From the description of operation i assume that should be performed rD = 0 as rs1 is negative. We also encountered similar issue with rs1 equal zero.

**Comment by davideschiavone** [comment]
Please, find the proposed fix at https://github.com/pulp-platform/riscv/commit/0cc75d1fcfd6c6a7b58014dd7bab903a80f8d90b

Waiting for feedback before merging to the master

**Comment by yaronbe1** [comment]
the fix fixed the above bug but introduced a new bug:

When rs1 is 1(0x00000001), rs2 is -370546197(0xE9E9E9EB). result should be -370546197(0xE9E9E9EB) but it's 370546196(0x16161614)  -  wrong

**Comment by davideschiavone** [comment]
is it the clipr or clipur?

**Comment by davideschiavone** [comment]
it is actually correct in case it is the clipr,

rs1 <= -(rs2 + 1), 1 <= -(-370546197+1) which is 370546196, so the result should be 0x16161616.

This comes from the fact that negB + 1 = -B, so the clip returns negB which is -B -1, i.e. -(B+1)

It that is the clipur , then it's a bug because it should return 0xE9E9E9EB.

**Comment by yaronbe1** [comment]
I am attaching the waves. 
please look at the time marker, AFAIK, the core is processing a clipur instruction:

![a](https://user-images.githubusercontent.com/50163944/65737393-0b1c9300-e0e7-11e9-8ac8-4749d02102c8.PNG)

**Comment by davideschiavone** [comment]
yes Yaron you are righ, my bad.

this should fix it: 
https://github.com/pulp-platform/riscv/commit/8eec2b452c7ca1a7cf70970f0efb8c3c6005486f

Let me know whether this solves the issues, if so I merge to the master.

thanks
Davide

**Comment by yaronbe1** [comment]
still not robust enough:
clipur rs1 = 0, rs2 = ebebebe9  should give rd = 0 but real result rd = ebebebe9

**Comment by davideschiavone** [comment]
yet another tentative fix: https://github.com/pulp-platform/riscv/commit/53da0833e7b610852bc67db62d34f64ad4c5e32c

**Comment by yaronbe1** [comment]
no issues after this fix
you can commit

**Comment by davideschiavone** [comment]
Thanks a lot
